### PR TITLE
Upgrade travis dependencies to use Python 3.5 and php5.6

### PR DESCRIPTION
**Pull request by matslindh**

### CODE REVIEW

**Comment by andreasrs** [comment]
:wave: Cool I'll try to take this for a testrun this weekend.

**Comment by matslindh** [comment]
I'm still working out the last kinks of the PR, so I'll notify you when it's actually building on Travis CI again :-)

**Comment by matslindh** [comment]
This PR finally has a working Travis setup and implementation. The build is now broken because of actually broken tests, and not because of the environment. I'll merge it into master tomorrow unless you have any further notes.

After that I'll start working on the broken tests and add support for the user feature from Imbo 2.

**Comment by matslindh** [comment]
I guess we should also backport most of these fixes to the python2 branch to make that build again as well.

**Pull request merged**
